version: '3'
services:
  api:
    image: pedrlk/devops-docker:${IMAGE_TAG:-latest}
    build: .
    ports:
      - "1313:1313"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development