version: '3'
services:
  api:
    image: ${IMAGE_TAG:-pedrlk/devops-docker:latest}
    build: .
    ports:
      - "1313:1313"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development