name: Continuos Integration

on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Conteúdo do Repositório
        uses: actions/checkout@v4
        #
      - name: Construir Imagem Docker
        run: docker build . --file Dockerfile --tag pedrhnttz/devops-lab-final:${{ github.sha }}
        #
      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        #
      - name: Push da Imagem Docker para o Docker Hub
        run: docker push pedrhnttz/devops-lab-final:${{ github.sha }}

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Conteúdo do Repositório
        uses: actions/checkout@v4
        #
      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        #
      - name: Puxar Imagem Docker para Teste
        run: docker pull pedrhnttz/devops-lab-final:${{ github.sha }}
        # 
      - name: Rodar Testes Unitários no Container Puxado
        run: docker-compose run api python -m unittest discover