name: Continuos Integration

on: 
  push:
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        #
      - name: Construir Imagem Docker
        run: docker build . --file Dockerfile --tag pedrhnttz/devops-lab-final:${{ github.sha }}