name: Continuos Integration

on: 
  push:
    branches: ["*"]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: pedrhnttz/devops-lab-final:${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Chechout repository
        uses: actions/checkout@v4
        #
      - name: Build docker image
        run: docker build . --file Dockerfile --tag pedrhnttz/devops-lab-final:${{ github.sha }}