name: Continuos Integration

on: 
  push:
    branches: ["*"]

permissions:
  contents: 'read'
  packages: 'write'

env:
  IMAGE_NAME: pedrlk/devops-docker

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: build docker image
        run: docker build -t imgDockerfile .


  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: run tests
        run: docker compose run imgDockerfile python -m unittest discover