name: Continuos Integration

on: 
  push:
    branches: ["*"]

permissions:
  contents: 'read'
  packages: 'write'

env:
  IMAGE_NAME: pedrlk/devops-docker

jobs:
  build: 
    runs-on: ubuntu-latest
    outputs:
      image_full_tag: ${{ env.IMAGE_NAME }}:latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: build docker image
        run: docker build . --file Dockerfile --tag ${{ env.IMAGE_NAME }}:latest
      - name: push image to docker hub
        run: |
          docker login -u pedrlk -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push ${{ env.IMAGE_NAME }}:latest

  test:
    needs: build
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ needs.build.outputs.image_full_tag }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: pull docker image
        run: |
          docker login -u pedrlk -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker pull ${{ env.IMAGE_TAG }}
      - name: bring up services with docker compose
        run: |
          docker compose up -d
          sleep 15
      - name: run tests
        run: docker-compose run api python -m unittest discover
      - name: teardown docker  compose services
        if: always()
        run: docker compose down