name: Continuos Integration

on: 
  push:
    branches: ["*"]

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: build docker image
        run: docker build -t devopslabfinal .


  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: run tests
        run: docker compose run devopslabfinal python -m unittest discover